require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoffeeShopsController do

  # This should return the minimal set of attributes required to create a valid
  # CoffeeShop. As you add validations to CoffeeShop, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoffeeShopsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all coffee_shops as @coffee_shops" do
      coffee_shop = CoffeeShop.create! valid_attributes
      get :index, {}, valid_session
      assigns(:coffee_shops).should eq([coffee_shop])
    end
  end

  describe "GET show" do
    it "assigns the requested coffee_shop as @coffee_shop" do
      coffee_shop = CoffeeShop.create! valid_attributes
      get :show, {:id => coffee_shop.to_param}, valid_session
      assigns(:coffee_shop).should eq(coffee_shop)
    end
  end

  describe "GET new" do
    it "assigns a new coffee_shop as @coffee_shop" do
      get :new, {}, valid_session
      assigns(:coffee_shop).should be_a_new(CoffeeShop)
    end
  end

  describe "GET edit" do
    it "assigns the requested coffee_shop as @coffee_shop" do
      coffee_shop = CoffeeShop.create! valid_attributes
      get :edit, {:id => coffee_shop.to_param}, valid_session
      assigns(:coffee_shop).should eq(coffee_shop)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CoffeeShop" do
        expect {
          post :create, {:coffee_shop => valid_attributes}, valid_session
        }.to change(CoffeeShop, :count).by(1)
      end

      it "assigns a newly created coffee_shop as @coffee_shop" do
        post :create, {:coffee_shop => valid_attributes}, valid_session
        assigns(:coffee_shop).should be_a(CoffeeShop)
        assigns(:coffee_shop).should be_persisted
      end

      it "redirects to the created coffee_shop" do
        post :create, {:coffee_shop => valid_attributes}, valid_session
        response.should redirect_to(CoffeeShop.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coffee_shop as @coffee_shop" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeShop.any_instance.stub(:save).and_return(false)
        post :create, {:coffee_shop => {  }}, valid_session
        assigns(:coffee_shop).should be_a_new(CoffeeShop)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeShop.any_instance.stub(:save).and_return(false)
        post :create, {:coffee_shop => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coffee_shop" do
        coffee_shop = CoffeeShop.create! valid_attributes
        # Assuming there are no other coffee_shops in the database, this
        # specifies that the CoffeeShop created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CoffeeShop.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => coffee_shop.to_param, :coffee_shop => { "these" => "params" }}, valid_session
      end

      it "assigns the requested coffee_shop as @coffee_shop" do
        coffee_shop = CoffeeShop.create! valid_attributes
        put :update, {:id => coffee_shop.to_param, :coffee_shop => valid_attributes}, valid_session
        assigns(:coffee_shop).should eq(coffee_shop)
      end

      it "redirects to the coffee_shop" do
        coffee_shop = CoffeeShop.create! valid_attributes
        put :update, {:id => coffee_shop.to_param, :coffee_shop => valid_attributes}, valid_session
        response.should redirect_to(coffee_shop)
      end
    end

    describe "with invalid params" do
      it "assigns the coffee_shop as @coffee_shop" do
        coffee_shop = CoffeeShop.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeShop.any_instance.stub(:save).and_return(false)
        put :update, {:id => coffee_shop.to_param, :coffee_shop => {  }}, valid_session
        assigns(:coffee_shop).should eq(coffee_shop)
      end

      it "re-renders the 'edit' template" do
        coffee_shop = CoffeeShop.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeShop.any_instance.stub(:save).and_return(false)
        put :update, {:id => coffee_shop.to_param, :coffee_shop => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coffee_shop" do
      coffee_shop = CoffeeShop.create! valid_attributes
      expect {
        delete :destroy, {:id => coffee_shop.to_param}, valid_session
      }.to change(CoffeeShop, :count).by(-1)
    end

    it "redirects to the coffee_shops list" do
      coffee_shop = CoffeeShop.create! valid_attributes
      delete :destroy, {:id => coffee_shop.to_param}, valid_session
      response.should redirect_to(coffee_shops_url)
    end
  end

end
